apiVersion: v1
kind: Service
metadata:
  name: datastore-frontend-lb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "traffic-port"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
spec:
  type: LoadBalancer
  selector:
    type: frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
