apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wordpress-mysql-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Ruchitbomboji/argocd-applications.git
        revision: main
        directories:
          - path: datastore-be
          - path: datastore-fe

  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Ruchitbomboji/Kubernetes.git
        targetRevision: main
        path: '{{path.basename}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: default

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
